package bot

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/MeteorsLiu/cibot/internal/toc"
	"github.com/google/go-github/v83/github"
)

func (b *Bot) updateTOC(ctx context.Context, client *github.Client, owner, index string, number int, projects []project, dir string) error {
	b.tocMu.Lock()
	defer b.tocMu.Unlock()

	var pending *github.PullRequest
	opts := &github.PullRequestListOptions{State: "open", Base: "main", ListOptions: github.ListOptions{PerPage: 100}}
	for {
		pulls, response, err := client.PullRequests.List(ctx, owner, index, opts)
		if err != nil {
			return err
		}
		for _, pull := range pulls {
			head := pull.GetHead()
			if head.GetRepo().GetFullName() == owner+"/"+index && strings.HasPrefix(head.GetRef(), "llarhub-bot/toc-pr-") {
				pending = pull
				break
			}
		}
		if pending != nil || response.NextPage == 0 {
			break
		}
		opts.Page = response.NextPage
	}
	branch := fmt.Sprintf("llarhub-bot/toc-pr-%d", number)
	base := "main"
	if pending != nil {
		branch = pending.GetHead().GetRef()
		base = branch
	}
	// Project inputs have been copied out; only root files are needed for the toc.
	if _, err := git(ctx, client, dir, "sparse-checkout", "set", "--cone"); err != nil {
		return err
	}
	// Fetch under tocMu: another delivery may have pushed after this clone began.
	if _, err := git(ctx, client, dir, "fetch", "--quiet", "origin", base); err != nil {
		return err
	}
	if _, err := git(ctx, client, dir, "checkout", "--quiet", "-B", branch, "FETCH_HEAD"); err != nil {
		return err
	}
	tocPath := filepath.Join(dir, "llarhub.toc")
	file, err := os.OpenFile(tocPath, os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}
	tocFile, err := toc.Parse(tocPath)
	if err != nil {
		return err
	}
	changed := false
	for _, project := range projects {
		added, err := tocFile.Add(project.name, project.source)
		if err != nil {
			return err
		}
		changed = changed || added
	}
	if !changed {
		return nil
	}
	if _, err := git(ctx, client, dir, "add", "--", "llarhub.toc"); err != nil {
		return err
	}
	if _, err := git(ctx, client, dir, "commit", "--quiet", "-m", fmt.Sprintf("Update llarhub.toc for PR #%d", number)); err != nil {
		return err
	}
	if _, err := git(ctx, client, dir, "push", "origin", "HEAD:refs/heads/"+branch); err != nil {
		return err
	}
	if pending != nil {
		return nil
	}
	pull, _, err := client.PullRequests.Create(ctx, owner, index, &github.NewPullRequest{
		Title: github.Ptr("Update LLAR Hub toc"),
		Head:  github.Ptr(branch), Base: github.Ptr("main"),
		Body: github.Ptr("Append source mappings for registered projects. Subsequent registration requests are accumulated in this PR. Generated by cibot."),
	})
	if err != nil {
		return err
	}
	log.Printf("bot: toc PR created repo=%s/%s url=%s", owner, index, pull.GetHTMLURL())
	return nil
}
